### ISSUE TITLE
Change "request" button for clarity

### ISSUE THREAD

**Issue by dolskar** [CryptoGrampy/HotShop#73]
If one was to post a link to their HotShop on their website or send the link to a customer, it's a little confusing to see 'request'. Something like 'checkout' or 'proceed with transaction' would make it more universal to function from the perspective of the vendor or customer. Other possible solutions would be to add a 'customer link' in addition to the admin and kiosk links or allow the admin to change the text.

(awesome work on the project gramps!)

**Comment by CryptoGrampy** [comment]
Hi @dolskar !  So HotShop is really geared toward in-person payments- when you the shop owner are there in person, you're able to see the green checkmark and validate that the customer's payment went through without the need to get a wallet involved.  

If you're looking to send invoices to a customer, you really should be using something like BTCPayServer which will keep track of outstanding invoices, etc.  One of HotShop's features is that it doesn't really have a loading time like a typical wallet.  If you open up your HotShop a month from now, it will load in the same time as it does today (a little on the slow side at the moment!), but it's still faster than a month of wallet syncing.  The downside to this is that your HotShop doesn't keep track of outstanding invoices or received payments.  

That said, it would be great to kind of better understand what you're trying to do- are you trying to add something like a 'donate .0001 xmr' button to your website or be able to send a link to a customer or friend that is like 'please pay .0001 xmr to X address' with the goal being your customer gets to see that the payment went through correctly?

**Comment by CryptoGrampy** [comment]
Might be resolved by: https://github.com/CryptoGrampy/HotShop/issues/89 . Closing issue.
